[tool.poetry]
name = "pytch-build"
version = "0.1.0"
description = "Assemble Pytch website from content, IDE, and tutorials"
homepage = "https://github.com/pytchlang/pytch-build"
authors = ["Ben North <ben@redfrontdoor.org>"]
license = "GPL-3.0-or-later"
readme = "README.rst"
packages = [{include = "pytchbuild"}]

[tool.poetry.dependencies]
python = "^3.9"
pygit2 = ">=1.2.1"
Markdown = ">=3.2.2"
beautifulsoup4 = ">=4.9.1"
click = ">=7.1.0"
watchdog = ">=0.10.3"
websockets = ">=8.1"
janus = ">=0.5.0"
pyyaml = ">=5.3.1"
colorlog = ">=4.2.1"
Pillow = ">=9.0.0"
requests = ">=2.31.0"

[tool.poetry.scripts]
pytchbuild = "pytchbuild.cli:main"
pytchbuild-watch = "pytchbuild.watch:main"
pytchbuild-gather-tutorials = "pytchbuild.gather_tutorials:main"
pytchbuild-new-tutorial = "pytchbuild.new_tutorial:main"
pytchbuild-gather-asset-media = "pytchbuild.gather_asset_media:main"
pytchbuild-gather-asset-credits = "pytchbuild.gather_asset_credits:main"

[tool.poetry.group.dev.dependencies]
tox = ">=4.4.6"
pytest = "^6.0.0"
flake8 = ">=3.8.3"
sphinx = ">=3.1.2"
sphinx-rtd-theme = ">=0.5.0"
sphinx-autobuild = ">=2020.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
