[project]
name = "pytch-build"
version = "0.1.0"
description = "Assemble Pytch website from content, IDE, and tutorials"
authors = [
    {name = "Ben North",email = "ben.north@tcd.ie"}
]
license = {text = "GPL-3.0-or-later"}
readme = "README.rst"
requires-python = ">=3.10,<4.0"
dependencies = [
    "pygit2 (==1.16.0)",
    "markdown (>=3.7,<4.0)",
    "beautifulsoup4 (>=4.12.3,<5.0.0)",
    "click (>=8.1.8,<9.0.0)",
    "watchdog (>=6.0.0,<7.0.0)",
    "websockets (>=14.1,<15.0)",
    "janus (>=2.0.0,<3.0.0)",
    "pyyaml (>=6.0.2,<7.0.0)",
    "colorlog (>=6.9.0,<7.0.0)",
    "pillow (>=11.1.0,<12.0.0)",
    "requests (>=2.32.3,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [
    { include = "pytchbuild" },
]
